import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
// Prisma Client import - types are generated by prisma generate
import type { PrismaClient } from '@prisma/client';
import { PrismaClient as PrismaClientClass } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import { Sequelize } from 'sequelize';
import { User as TypeORMUser } from './entities/typeorm/user.entity';
import { Profile as TypeORMProfile } from './entities/typeorm/profile.entity';
import { Post as TypeORMPost } from './entities/typeorm/post.entity';
import { Tag as TypeORMTag } from './entities/typeorm/tag.entity';
import { User as SequelizeUser, initUserModel } from './models/sequelize/user.model';
import { Profile as SequelizeProfile, initProfileModel } from './models/sequelize/profile.model';
import { Post as SequelizePost, initPostModel } from './models/sequelize/post.model';
import { Tag as SequelizeTag, initTagModel } from './models/sequelize/tag.model';

/**
 * ORM Service
 * Demonstrates how to use Prisma, TypeORM, and Sequelize
 * All three ORMs work with the same database structure
 */
@Injectable()
export class OrmService implements OnModuleInit {
  private prisma: PrismaClientClass;
  private sequelize: Sequelize;

  constructor(
    @InjectRepository(TypeORMUser, 'orm')
    private typeormUserRepo: Repository<TypeORMUser>,
    @InjectRepository(TypeORMProfile, 'orm')
    private typeormProfileRepo: Repository<TypeORMProfile>,
    @InjectRepository(TypeORMPost, 'orm')
    private typeormPostRepo: Repository<TypeORMPost>,
    @InjectRepository(TypeORMTag, 'orm')
    private typeormTagRepo: Repository<TypeORMTag>,
  ) {
    // Prisma 7: Build connection URL
    const databaseUrl = `postgresql://${process.env.DB_USERNAME || 'postgres'}:${process.env.DB_PASSWORD || 'postgres'}@${process.env.DB_HOST || 'localhost'}:${process.env.DB_PORT || '5432'}/${process.env.DB_NAME || 'core_concepts'}`;
    
    // Prisma 7: Create pg Pool and adapter
    const pool = new Pool({ connectionString: databaseUrl });
    const adapter = new PrismaPg(pool);
    
    // Prisma 7 requires adapter to be passed to constructor
    this.prisma = new PrismaClientClass({ adapter });
    this.sequelize = new Sequelize({
      dialect: 'postgres',
      host: process.env.DB_HOST || 'localhost',
      port: parseInt(process.env.DB_PORT || '5432', 10),
      username: process.env.DB_USERNAME || 'postgres',
      password: process.env.DB_PASSWORD || 'postgres',
      database: process.env.DB_NAME || 'core_concepts',
      logging: false,
    });
  }

  async onModuleInit() {
    // Initialize Sequelize models
    initUserModel(this.sequelize);
    initProfileModel(this.sequelize);
    initPostModel(this.sequelize);
    initTagModel(this.sequelize);

    // Define associations
    SequelizeUser.hasOne(SequelizeProfile, { foreignKey: 'userId', as: 'profile' });
    SequelizeProfile.belongsTo(SequelizeUser, { foreignKey: 'userId', as: 'user' });
    SequelizeUser.hasMany(SequelizePost, { foreignKey: 'authorId', as: 'posts' });
    SequelizePost.belongsTo(SequelizeUser, { foreignKey: 'authorId', as: 'author' });
    SequelizeUser.belongsToMany(SequelizeTag, {
      through: 'orm_user_tags',
      foreignKey: 'userId',
      otherKey: 'tagId',
      as: 'tags',
    });
    SequelizeTag.belongsToMany(SequelizeUser, {
      through: 'orm_user_tags',
      foreignKey: 'tagId',
      otherKey: 'userId',
      as: 'users',
    });
  }

  /**
   * PRISMA EXAMPLES
   */

  async createUserWithPrisma(data: { name: string; email: string }) {
    return await this.prisma.user.create({
      data,
      include: {
        profile: true,
        posts: true,
        tags: true,
      },
    });
  }

  async findUserWithPrisma(id: number) {
    return await this.prisma.user.findUnique({
      where: { id },
      include: {
        profile: true,
        posts: true,
        tags: true,
      },
    });
  }

  async findAllUsersWithPrisma() {
    return await this.prisma.user.findMany({
      include: {
        profile: true,
        posts: true,
        tags: true,
      },
    });
  }

  /**
   * TYPEORM EXAMPLES
   */

  async createUserWithTypeORM(data: { name: string; email: string }) {
    const user = this.typeormUserRepo.create(data);
    return await this.typeormUserRepo.save(user);
  }

  async findUserWithTypeORM(id: number) {
    return await this.typeormUserRepo.findOne({
      where: { id },
      relations: ['profile', 'posts', 'tags'],
    });
  }

  async findAllUsersWithTypeORM() {
    return await this.typeormUserRepo.find({
      relations: ['profile', 'posts', 'tags'],
    });
  }

  /**
   * SEQUELIZE EXAMPLES
   */

  async createUserWithSequelize(data: { name: string; email: string }) {
    return await SequelizeUser.create(data, {
      include: [
        { model: SequelizeProfile, as: 'profile' },
        { model: SequelizePost, as: 'posts' },
        { model: SequelizeTag, as: 'tags' },
      ],
    });
  }

  async findUserWithSequelize(id: number) {
    return await SequelizeUser.findByPk(id, {
      include: [
        { model: SequelizeProfile, as: 'profile' },
        { model: SequelizePost, as: 'posts' },
        { model: SequelizeTag, as: 'tags' },
      ],
    });
  }

  async findAllUsersWithSequelize() {
    return await SequelizeUser.findAll({
      include: [
        { model: SequelizeProfile, as: 'profile' },
        { model: SequelizePost, as: 'posts' },
        { model: SequelizeTag, as: 'tags' },
      ],
    });
  }

  /**
   * Get code examples for frontend display
   */
  getCodeExamples() {
    return {
      prisma: {
        schema: this.getPrismaSchemaExample(),
        usage: this.getPrismaUsageExample(),
      },
      typeorm: {
        entity: this.getTypeORMEntityExample(),
        usage: this.getTypeORMUsageExample(),
      },
      sequelize: {
        model: this.getSequelizeModelExample(),
        usage: this.getSequelizeUsageExample(),
      },
    };
  }

  private getPrismaSchemaExample(): string {
    return `// Prisma Schema (schema.prisma)
model User {
  id        Int      @id @default(autoincrement())
  name      String   @db.VarChar(100)
  email     String   @unique @db.VarChar(255)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  profile Profile?
  posts   Post[]
  tags    Tag[]

  @@index([email])
  @@map("orm_users")
}`;
  }

  private getPrismaUsageExample(): string {
    return `// Prisma Usage
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({
  datasourceUrl: process.env.DATABASE_URL
});

// Create
const user = await prisma.user.create({
  data: { name: 'John', email: 'john@example.com' }
});

// Find with relations
const userWithRelations = await prisma.user.findUnique({
  where: { id: 1 },
  include: { profile: true, posts: true, tags: true }
});

// Update
await prisma.user.update({
  where: { id: 1 },
  data: { name: 'Jane' }
});

// Delete
await prisma.user.delete({ where: { id: 1 } });`;
  }

  private getTypeORMEntityExample(): string {
    return `// TypeORM Entity
import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity('orm_users')
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 100 })
  name: string;

  @Column({ type: 'varchar', length: 255, unique: true })
  email: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @OneToOne(() => Profile, profile => profile.user)
  profile: Profile;

  @OneToMany(() => Post, post => post.author)
  posts: Post[];

  @ManyToMany(() => Tag, tag => tag.users)
  @JoinTable()
  tags: Tag[];
}`;
  }

  private getTypeORMUsageExample(): string {
    return `// TypeORM Usage
import { Repository } from 'typeorm';

// Inject repository
constructor(
  @InjectRepository(User)
  private userRepo: Repository<User>
) {}

// Create
const user = this.userRepo.create({ name: 'John', email: 'john@example.com' });
await this.userRepo.save(user);

// Find with relations
const userWithRelations = await this.userRepo.findOne({
  where: { id: 1 },
  relations: ['profile', 'posts', 'tags']
});

// Update
await this.userRepo.update(1, { name: 'Jane' });

// Delete
await this.userRepo.delete(1);`;
  }

  private getSequelizeModelExample(): string {
    return `// Sequelize Model
import { Model, DataTypes, Sequelize } from 'sequelize';

export class User extends Model {
  declare id: number;
  declare name: string;
  declare email: string;
}

User.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  name: {
    type: DataTypes.STRING(100),
    allowNull: false
  },
  email: {
    type: DataTypes.STRING(255),
    allowNull: false,
    unique: true
  }
}, {
  sequelize,
  modelName: 'User',
  tableName: 'orm_users'
});`;
  }

  private getSequelizeUsageExample(): string {
    return `// Sequelize Usage
import { User } from './models/user.model';

// Create
const user = await User.create({
  name: 'John',
  email: 'john@example.com'
});

// Find with relations
const userWithRelations = await User.findByPk(1, {
  include: [
    { model: Profile, as: 'profile' },
    { model: Post, as: 'posts' },
    { model: Tag, as: 'tags' }
  ]
});

// Update
await user.update({ name: 'Jane' });

// Delete
await user.destroy();`;
  }
}

